import { ClerkProvider } from '@clerk/nextjs';

import { Roboto } from 'next/font/google';
import { Navigation } from '@/components/navigation';
import './globals.css';

const inter = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  preload: true,
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={inter.className}>
          <main className='h-full'>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
